package com.keke.roomlib.zego;

public enum VoicesStates {

    VOICE_EVENT_JOIN_OK,
    VOICE_EVENT_JOIN_FAILED,
    VOICE_EVENT_LEAVED_ALL,
    VOICE_EVENT_RECONNECTING,
    VOICE_EVENT_BGM_STOPPED,
    VOICE_EVENT_MESSAGE_NOTIFY,
    VOICE_EVENT_OTHERS_VOICE,
    VOICE_EVENT_NET_WORK_QUALITY,
    VOICE_EVENT_REMOTE_AUDIO_STATS,
    ;


}
